[workspace]
resolver = "2"
members = [
    "crates/akapen-core",
    "crates/akapen-io",
    "crates/akapen-ffi",
    "crates/akapen-render",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/yosshibox/akapen"
authors = ["Akapen contributors"]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
